language: node_js
node_js:
  - "6.9"

#branches:
#  only:
#    - develop
#    - master

before_script:
  - npm i -g @angular/cli

script:
  - ng lint
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
